### ISSUE TITLE
[FEATURE] Add search functionality.

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/TrendTrack#15]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Hello:)
We should add a search bar so the users can search the repos

### Proposed Solution

Add a search bar to search the visible repos.

### Do you want to work on this issue?

No

**Comment by wlanhage** [comment]
I would like to look into this issue!

**Comment by Bashamega** [comment]
> I would like to look into this issue!
Sure
