### ISSUE TITLE
[FEATURE] Dropdown to select daily/weekly/monthly trending

### ISSUE THREAD

**Issue by eddiejaoude** [Bashamega/TrendTrack#24]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The API has daily/weekly/monthly trending repos, docs are here https://github.com/EddieHubCommunity/github-trending-repos?tab=readme-ov-file#requests

### Proposed Solution

Dropdown for the user to select the trending type next to the date picker. Default to daily.

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
Thank you very much. I will work on it
