### ISSUE TITLE
[FEATURE] It would be nice to have the date set to today/yesterday when you launch the app

### ISSUE THREAD

**Issue by byhlel** [Bashamega/TrendTrack#27]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When launching the app no date is selected and it would be a nice improvement to have one by default!

### Proposed Solution

I think in most cases it's more suitable to display yesterday's results by default as depending on when you check the page today will often appear with no data.

### Screenshots

![image](https://github.com/user-attachments/assets/6d910402-d2be-4f3c-add6-5f0bea707718)

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
Thanks. I will work on it
