### ISSUE TITLE
[FEATURE] Add the ability to hide repositories you reviewed

### ISSUE THREAD

**Issue by wiki-me** [Bashamega/TrendTrack#38]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When looking at the list of trending repositories , the user might have to repeatedly continue scroll over repositories he already reviewed.

### Proposed Solution

Add a button to hide repositories, so they won't be shown again, possibly with a page that shows the hidden repositories (in case you accidently pressed the button)

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
Great feature

**Comment by kvtemadden** [comment]
Hey @Bashamega, am I alright to pick this up?

**Comment by Bashamega** [comment]
> Hey @Bashamega, am I alright to pick this up? 

Of course

**Comment by wiki-me** [comment]
Thanks for adding this feature (its a significant upgrade over github IMO), but clicking on "viewed repos" after viewing repos and even hiding them after clicking "hide viewed" shows nothing ("no data!").

**Comment by Bashamega** [comment]
> Thanks for adding this feature (its a significant upgrade over github IMO), but clicking on "viewed repos" after viewing repos and even hiding them after clicking "hide viewed" shows nothing ("no data!").

Thank you for reporting this issue. @kvtemadden Can you fix this issue in another pr? Thanks

**Comment by kvtemadden** [comment]
Hey @wiki-me, could you send a screen recording? I've tried to repro but I haven't been able to.

Here's what happens my end (this is at [TrendTrack](https://trendtrack.vercel.app/))

![Screen Recording 2024-10-07 at 12 12 14](https://github.com/user-attachments/assets/684abe8b-2471-44be-ae02-f064d8d98128)

**Comment by wiki-me** [comment]
![simplescreenrecorder-2024-10-07_19 24 38](https://github.com/user-attachments/assets/aec7ead8-c769-4ab0-8d12-ef266360dbd6)

The web console messages also seems relevant:

[console-export-2024-10-7_19-28-43.txt](https://github.com/user-attachments/files/17281773/console-export-2024-10-7_19-28-43.txt)

**Comment by wiki-me** [comment]
It will also be good to remember the setting to "hide viewed", so if i return to the page later the viewed repositories will still be hided

**Comment by kvtemadden** [comment]
Cheers for sharing that. Are you using IE as a browser?

>  remember the setting to "hide viewed"

I'll also add that ability in too.

**Comment by Bashamega** [comment]
Sure that would be great. Thank you @kvtemadden

**Comment by wiki-me** [comment]
> Cheers for sharing that. Are you using Edge as a browser?

its on debian 12 , both on firefox ESR  - "128.3.0esr (64-bit)" and on chromium - "Version 129.0.6668.89 (Official Build)".

**Comment by Bashamega** [comment]
@wiki-me Can you check #68 ?
