### ISSUE TITLE
Making the website responsive and interactive

### ISSUE THREAD

**Issue by AdarshRaj241408** [Bashamega/TrendTrack#45]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The UI/UX is a bit bland, I Saw an issue raised with adding flexbox and more colour gradients. We could add some features to make it more interactive.
Also there is not much info about the repo on main page.

### Proposed Solution

-Added an assets folder with starImage.svg and forkImage.svg to make the UI more pleasent.
Added Hover effect on Repo cards so that they scale-up on hovering.
Added the prominent language used in the repo so users find it easier to select the repositries they are interested in.

### Screenshots

![Screenshot_20241003_104258_GitHub](https://github.com/user-attachments/assets/30bb5248-d89d-4891-9b93-8701b3b9f7e1)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Already made the changes and Added a PR.

**Comment by AdarshRaj241408** [comment]
This is the PR with just basic enhancement features.

**Comment by Bashamega** [comment]
Sure you can open a pr now:)
Thanks for raising the issue
