### ISSUE TITLE
Enhancing UX: Adding Hero Section, Custom Logo, & Possible Navigation

### ISSUE THREAD

**Issue by clydehenry3** [Bashamega/TrendTrack#51]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, the feature request is related to improving the user experience by adding essential elements that are currently missing to develop additional trust/usability of TrendTrack. Specifically, the absence of a hero section, custom logo, and navigation (if needed) impacts how much trust the user has and usability of the website. These changes should make it more engaging for users and you as the product owner.

### Proposed Solution

The proposed solution involves:
1. Implementing a visually appealing hero section that captures user attention
2. Integrating a customizable logo to enhance branding
3. Adding or refining the navigation to improve the overall user flow and accessibility (optional because of how lean the app is)
4. 
5. This will create a more cohesive and user-friendly interface, making it easier for users to engage with the site and find relevant information.

### Screenshots

![TrendTrack Changes](https://github.com/user-attachments/assets/d58aa3e6-5c79-4739-9ed8-0f6074156549)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

**Hero Section:**
-Create a reusable Hero component that includes a title, description, and CTA button.
-Use Tailwind CSS for responsive design, ensuring the section is visually appealing on all screen sizes.

**Custom Logo:**
-Add a Logo component that accepts a customizable logo image file.
- Place the logo in the site's header component, ensuring it scales properly using Tailwind’s utility classes like h-12 or w-12 for responsive sizing.

**Navigation (optional)**
-Implement a Navigation bar at the top using React components.
-Use Tailwind’s flex and space-x-* utilities to position links for a clean and responsive layout.

**Comment by Bashamega** [comment]
Nice idea.
Thanks for raising the issue

**Comment by Bashamega** [comment]
But can you show me the logo first?

**Comment by clydehenry3** [comment]
> But can you show me the logo first?

I am going to create one from scratch! Is there anything you would like implemented on such as shapes, letters, etc. I need to create it first.

**Comment by Bashamega** [comment]
> > But can you show me the logo first?
> 
> I am going to create one from scratch! Is there anything you would like implemented on such as shapes, letters, etc. I need to create it first. 

I don't have anything in mind

**Comment by clydehenry3** [comment]
> > > But can you show me the logo first?
> > 
> > 
> > I am going to create one from scratch! Is there anything you would like implemented on such as shapes, letters, etc. I need to create it first.
> 
> I don't have anything in mind

Let me create a couple of different iterations and then I can send you them on Discord before I implement it within the design. Going to send you a friend request now.

**Comment by clydehenry3** [comment]
Hey @Bashamega! Here are some logo options. I was unsure about the accent colors so I went with blue for trust. 

Here is a breakdown:

- Magnifying Glass: Represents research, exploration, and discovery.
- </> Symbol: Symbolizes coding, programming, and the digital world.
- Stats arrows: Represents data, metrics, and measurement, and based off the word trends. 

Then when working with the stats icon, I could see that there were "Ts" involved and figured it was a good time to make the logo a little more intuitive. 

Let me know what you think and happy to change the colors if needed. 
![Logo Options](https://github.com/user-attachments/assets/1158ef16-bd55-41cf-b329-bf0ad2e363fa)

**Comment by Bashamega** [comment]
> Hey @Bashamega! Here are some logo options. I was unsure about the accent colors so I went with blue for trust. 
> 
> Here is a breakdown:
> 
> - Magnifying Glass: Represents research, exploration, and discovery.
> - </> Symbol: Symbolizes coding, programming, and the digital world.
> - Stats arrows: Represents data, metrics, and measurement, and based off the word trends. 
> 
> Then when working with the stats icon, I could see that there were "Ts" involved and figured it was a good time to make the logo a little more intuitive. 
> 
> Let me know what you think and happy to change the colors if needed. 
> ![Logo Options](https://github.com/user-attachments/assets/1158ef16-bd55-41cf-b329-bf0ad2e363fa)
> 

The second one looks great. Thank you

**Comment by clydehenry3** [comment]
> > Hey @Bashamega! Here are some logo options. I was unsure about the accent colors so I went with blue for trust.
> > Here is a breakdown:
> > 
> > * Magnifying Glass: Represents research, exploration, and discovery.
> > * </> Symbol: Symbolizes coding, programming, and the digital world.
> > * Stats arrows: Represents data, metrics, and measurement, and based off the word trends.
> > 
> > Then when working with the stats icon, I could see that there were "Ts" involved and figured it was a good time to make the logo a little more intuitive.
> > Let me know what you think and happy to change the colors if needed.
> > ![Logo Options](https://private-user-images.githubusercontent.com/122248042/373420590-1158ef16-bd55-41cf-b329-bf0ad2e363fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMDQ4NDcsIm5iZiI6MTcyODAwNDU0NywicGF0aCI6Ii8xMjIyNDgwNDIvMzczNDIwNTkwLTExNThlZjE2LWJkNTUtNDFjZi1iMzI5LWJmMGFkMmUzNjNmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwMTE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDAyNTg0Njc4Mzc5YzFkOGRlYmFiYjhmZGEyZGU1MmQyYzhhZGEzMTM2ZWE3NmExZGQ4MTViNzE5YjIwNTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nJKiYE6RwXMuhfdRafUGnwiBKZscAPz5-yt7c_Y-nXs)
> 
> The second one looks great. Thank you

I did submit one PR that has a filler logo in there. Would you be okay if I submitted a second issue/PR that has be replace that filler logo? 

Glad you like the logo!

**Comment by Bashamega** [comment]
> > > Hey @Bashamega! Here are some logo options. I was unsure about the accent colors so I went with blue for trust.
> > > Here is a breakdown:
> > > 
> > > * Magnifying Glass: Represents research, exploration, and discovery.
> > > * </> Symbol: Symbolizes coding, programming, and the digital world.
> > > * Stats arrows: Represents data, metrics, and measurement, and based off the word trends.
> > > 
> > > Then when working with the stats icon, I could see that there were "Ts" involved and figured it was a good time to make the logo a little more intuitive.
> > > Let me know what you think and happy to change the colors if needed.
> > > ![Logo Options](https://private-user-images.githubusercontent.com/122248042/373420590-1158ef16-bd55-41cf-b329-bf0ad2e363fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMDQ4NDcsIm5iZiI6MTcyODAwNDU0NywicGF0aCI6Ii8xMjIyNDgwNDIvMzczNDIwNTkwLTExNThlZjE2LWJkNTUtNDFjZi1iMzI5LWJmMGFkMmUzNjNmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwMTE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDAyNTg0Njc4Mzc5YzFkOGRlYmFiYjhmZGEyZGU1MmQyYzhhZGEzMTM2ZWE3NmExZGQ4MTViNzE5YjIwNTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nJKiYE6RwXMuhfdRafUGnwiBKZscAPz5-yt7c_Y-nXs)
> > 
> > 
> > The second one looks great. Thank you
> 
> I did submit one PR that has a filler logo in there. Would you be okay if I submitted a second issue/PR that has be replace that filler logo?
> 
> Glad you like the logo!

You can just push a new commit on the same branch which will auto update the pr
