### ISSUE TITLE
[BUG] Replace Hero Image

### ISSUE THREAD

**Issue by clydehenry3** [Bashamega/TrendTrack#55]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The current hero image that is in the code base is super blurry on the mobile device and would love to improve this for the product. Additionally, I will see if I can make the image full-width of the mobile screen. 

### Steps to Reproduce

Loaded TrendTrack on my mobile device and could not see the hero image clearly.

### Screenshots

![IMG_1162](https://github.com/user-attachments/assets/3167b8fc-1318-468f-863e-f238ef760ecf)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I plain to implement this by going back into Figma and optimizing the photo. Additionally, I configure the image size to be full width by going through Tailwind documentation.

**Comment by Bashamega** [comment]
nice

**Comment by clydehenry3** [comment]
Is there anyway to add a hacktobestfest label?

**Comment by Bashamega** [comment]
I have added it for you
