### ISSUE TITLE
[Jerk on Hover] : There is a jerk on hover

### ISSUE THREAD

**Issue by shobhit15082003** [Bashamega/TrendTrack#64]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There is a jerk on hover which doesn't look good.

### Proposed Solution

Added delay and transition to make it smooth.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Added delay and transition to make it smooth.

**Comment by Bashamega** [comment]
Nice idea.
