### ISSUE TITLE
[BUG] Github and its Icon are connected in header.

### ISSUE THREAD

**Issue by wlanhage** [Bashamega/TrendTrack#69]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Maybe add a very small margin/gap between the Github text and its icon in header. 

### Steps to Reproduce

Include any relevant details like:

Homepage/header

### Screenshots

<img width="84" alt="Screenshot 2024-10-09 at 18 18 10" src="https://github.com/user-attachments/assets/e10d44fc-8391-4302-b901-61e02cd28570">

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
Thanks for raising this issue

**Comment by Bashamega** [comment]
Sure @annuk123
