### ISSUE TITLE
[FEATURE] Create a footer

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/TrendTrack#75]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Create a footer

### Proposed Solution

Create the footer with copyright and the current version of the website.

### Do you want to work on this issue?

No

**Comment by Piyush-Tilokani** [comment]
Yes i would like to work on this issue/feature
I went through the code base and noticed you used tailwind for styling so i will add a footer using some pre-built tailwind footer template and customize it according to the need of the site

**Comment by Bashamega** [comment]
Thanks @Piyush-Tilokani
