### ISSUE TITLE
[FEATURE] Add the logo as a favicon

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/TrendTrack#78]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently we have a logo but it is not set as the favicon.

### Proposed Solution

Modify the layout page to add the custom favicon

### Do you want to work on this issue?

No

**Comment by CityIsBetter** [comment]
i would like to take on this issue
