### ISSUE TITLE
[FEATURE] Create a better readme

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/TrendTrack#8]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Hello:)
This project is missing a readme.

### Proposed Solution

The readme should have a preview and badges and a description.

### Do you want to work on this issue?

No

**Comment by byhlel** [comment]
I might have a look at it when I have some time, any idea at what kind of badges you want to display?

**Comment by Bashamega** [comment]
> I might have a look at it when I have some time, any idea at what kind of badges you want to display?
Sure. You can make it similar to this: https://github.com/Bashamega/WebDevTools/blob/main/README.md
