### ISSUE TITLE
[FEATURE] Making the Navbar sticky and Fixing "Check Trends" Button.

### ISSUE THREAD

**Issue by Shrey0610** [Bashamega/TrendTrack#81]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I often find it frustrating when navigating the page because the navbar is not sticky, making it hard to access different sections easily. Additionally, the "Check Trends" button previously did not function, which left users unable to scroll directly to the "Repos" section.

### 'Nav.tsx'- (in line 16)
```  <nav className="bg-gray-800 p-4 w-screen sticky top-0 z-50"> ```

### 'Hero.tsx'- 
I have implemented a new function called scrollToRepoControls that enhances the user experience by smoothly scrolling the page to the "Repo Controls" section when invoked.

And for that the button is-
>  ``` <button className="btn btn-primary w-1/2" onClick={scrollToRepoControls}>Check Trends</button>```

 ### 'Repos.tsx'-
 And repos is-
> ```<div id="repo-controls" className="flex items-center justify-between p-5 flex-col md:flex-row md:space-x-2 md:items-center mx-auto pt-20 pb-10"> ```

### Nav.tsx-
<img width="1354" alt="Screenshot 2024-10-14 at 01 04 43" src="https://github.com/user-attachments/assets/5e0f7688-7574-4f8f-8bd7-27977eb3f335">

### Hero.tsx-
<img width="1354" alt="Screenshot 2024-10-14 at 01 00 54" src="https://github.com/user-attachments/assets/66e02ff0-941c-42f3-b547-4fcbdaf69fbe">

### Repos.tsx-
<img width="1354" alt="Screenshot 2024-10-14 at 01 06 31" src="https://github.com/user-attachments/assets/4bae399c-33fd-447c-a746-7ad2f205fda6">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I updated the <nav> element's class to include sticky and top-0. To further enhance navigation, I updated the functionality of the "Check Trends" button in the Hero.tsx component to smoothly scroll to the "Repos" section when clicked. Finally, I ensured that the "Repos" section has a corresponding ID in the Repos.tsx component to facilitate smooth scrolling.

**Comment by Shrey0610** [comment]
@Bashamega, I'm very new to contributing, so please check this. I have participated in 'gssoc-ext' and 'hacktoberfest' this time so if this issue and solution suits you than please assign these labels to me.
Thank you.

**Comment by Bashamega** [comment]
Nice catch @Shrey0610. Thank you for raising the issue

**Comment by Shrey0610** [comment]
Can you please assign me with 'gssoc-ext' and 'hacktoberfest' labels to me

**Comment by Bashamega** [comment]
> Can you please assign me with 'gssoc-ext' and 'hacktoberfest' labels to me

We are not participating in gssoc but we are participating in Hacktoberfest. I have added its label.

**Comment by Shrey0610** [comment]
I have created a PR, please check and merge it. Thank you

**Comment by Shrey0610** [comment]
Thank you
