### ISSUE TITLE
NavBar should be sticky

### ISSUE THREAD

**Issue by annuk123** [Bashamega/TrendTrack#90]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I think, Sticky navbar looks more attractive

### Proposed Solution

So, I want to make navbar as sticky

### Do you want to work on this issue?

Yes

**Comment by Bashamega** [comment]
This is a duplicate of #81

**Comment by annuk123** [comment]
> This is a duplicate of #81

Sorry I didn't saw
